export const refs = {
  searchForm: document.querySelector('.search'),
  btnSearchFilms: document.querySelector('.search__button'),
  glideSlides: document.querySelector('.glide__slides'),
  topFilms: document.querySelector('.top-films'),
  productsList: document.querySelector('.films'),
  filmsContainer: document.querySelector('.js-films-container'),
  searchFilms: document.querySelector('.search-films'),
  paginationContainer: document.querySelector('#tui-pagination-container'),
  arrowLeft: document.querySelector('.arrow_left'),
  arrowRight: document.querySelector('.arrow_right'),
  pageNumbers: document.querySelector('.page-numbers'),
  inputEl: document.getElementById('searchQuery'),
  infoTextEl: document.querySelector('.info-text'),
  btnLoadMoreEl: document.querySelector('.load-more'),
  teamModal: document.querySelector('.team_modal'),
  teamModalCloseBtn: document.querySelector('.teamModal__close__btn'),
  teamOpenModalBtn: document.querySelector('.team_modal_btn'),
  paginationList: document.querySelector('.tui-pagination'),
};
